### PR TITLE
fix: use correct chunk size default unit

### LINKED ISSUE #115: Default chunk size is using wrong unit
My team is running into timeout issues while uploading files from iOS. We use the `defaultDirectUploadChunkSize` property which sets the default chunk size to 8 MB. According to [Google Cloud's upload documentation](https://cloud.google.com/storage/docs/performing-resumable-uploads#chunked-upload) and other initializers for `DirectUploadOptions.Transport` this should be specified as 8 MiB (mebibytes). 

In my testing this fixed our upload timeout issues.

### PR DESCRIPTION
**Pull request by andrewjl-mux**
See [GCP docs](https://cloud.google.com/storage/docs/performing-resumable-uploads#chunked-upload). Fixes #115.

### CODE REVIEW

File: Sources/MuxUploadSDK/PublicAPI/Options/DirectUploadOptions.swift [hunk 1]
```diff
@@ -307,7 +322,7 @@ extension Measurement where UnitType == UnitInformationStorage {
     public static var defaultDirectUploadChunkSize: Self {
         Measurement(
             value: 8,
-            unit: .megabytes
+            unit: .mebibytes
```
Comment (andrewjl-mux) [inline Sources/MuxUploadSDK/PublicAPI/Options/DirectUploadOptions.swift:325]: Unit change here

**Review by daytime-em — APPROVED** [review]
Lgtm!
